### ISSUE TITLE
about retarget data

### ISSUE THREAD

**Issue by pipijiev12** [JingLi513/Audio2Gestures#15]
Currently I encounter a problem. I import fbx data into Maya. Do I need to use humanik to create a new model? Or author, can you provide smplx model?

**Comment by JingLi513** [comment]
I have upload a smplx model in fbx format. You could find it at the root path of the repo, which is named as "smpl.fbx".

**Comment by pipijiev12** [comment]
The author is very sorry. After looking at your demo.fbx model, I roughly understand the corresponding position of your skeleton. But I am new to the software Maya and not very familiar with the software Humanik. I'd like to watch your steps for binding the corresponding smplx model. If possible, can you record your operation steps as a video and send it to me privately? Or can you send out similar related tutorials?

**Comment by pipijiev12** [comment]
> I have upload a smplx model in fbx format. You could find it at the root path of the repo, which is named as "smpl.fbx".

The author is very sorry. After looking at your demo.fbx model, I roughly understand the corresponding position of your skeleton. But I am new to the software Maya and not very familiar with the software Humanik. I'd like to watch your steps for binding the corresponding smplx model. If possible, can you record your operation steps as a video and send it to me privately? Or can you send out similar related tutorials?

**Comment by pipijiev12** [comment]
> I have upload a smplx model in fbx format. You could find it at the root path of the repo, which is named as "smpl.fbx".

The author is very sorry. After looking at your demo.fbx model, I roughly understand the corresponding position of your skeleton. But I am new to the software Maya and not very familiar with the software Humanik. I'd like to watch your steps for binding the corresponding smplx model. If possible, can you record your operation steps as a video and send it to me privately? Or can you send out similar related tutorials?
My email is ppj977617638@icloud.com
