### ISSUE TITLE
motion retargeting

### ISSUE THREAD

**Issue by ujemd** [JingLi513/Audio2Gestures#2]
Hi Jing Li,

I've found your article very interesting! I'd like to ask you what method did you use to retarget the data from the Trinity dataset to SMPLX model?

Thank you :)

**Comment by JingLi513** [comment]
Thanks for your interest in our work. We retarget the motion data to the SMPL-X model using MAYA's HumanIK.

**Comment by ujemd** [comment]
Thanks for the help!

**Comment by armored-guitar** [comment]
@ujemd Hi. Have you managed to retarget this motion? I have access to trinity dataset, but can't retarget motion. Can you please help

**Comment by ujemd** [comment]
@armored-guitar no, I'm sorry. I don't have access to Maya software at the moment.

**Comment by zhuangzhuang000** [comment]
> @ujemd Hi. Have you managed to retarget this motion? I have access to trinity dataset, but can't retarget motion. Can you please help

Hello, I have the same problem. Have you solved it? can you tell me how to do it?
